(function(){
 const version='2026-10-10',origin='https://login.liqkoargentina.workers.dev',native=window.fetch.bind(window);
 const declaration='Declaro que la información y el contenido que publico son veraces, que cuento con los derechos y autorizaciones necesarios y que cumplen las normas de la plataforma. Asumo la responsabilidad por esta publicación.';
 const terms='Al usar Guía Local, me comprometo a publicar información veraz, contar con las autorizaciones necesarias y respetar las normas de la plataforma. No publicaré contenido que promueva violencia, acoso, abuso, explotación o actividades ilícitas. La plataforma puede restringir o retirar publicaciones que incumplan estas condiciones. Marcar +18 no permite contenido prohibido.';
 const explanation='Marcá Sí si ofrecés contenido, productos, servicios o espectáculos exclusivos para adultos. Requiere revisión y restringe la visualización a usuarios mayores de 18 años con sesión iniciada y aceptación de acceso. No reemplaza las condiciones de ingreso del evento.';
 const targets={eventos:'#ev-adulto',free:'#evf-adulto',actividades:'#act-adulto',publicidad:'#pub-adulto',anunciante:'[name="contenido_adulto"]',alta:'#btnEnviarAltaAnunciante',cuenta:'#register-btn'};
 function box(key,node){if(!node||document.getElementById('declaracion-'+key))return;const block=document.createElement('div');block.id='declaracion-'+key;block.style.cssText='margin:14px 0;padding:12px;border:1px solid #ddd;border-radius:8px';
  const details=document.createElement('details'),summary=document.createElement('summary'),p=document.createElement('p');summary.textContent='Términos de publicación';p.textContent=terms;details.append(summary,p);block.append(details);
  let label=document.createElement('label'),check=document.createElement('input');const legacy=key==='free'?document.getElementById('evf-responsabilidad'):null;if(legacy){label=legacy.closest('label');check=legacy;const text=label.querySelector('span');if(text)text.textContent=declaration;}else{check.type='checkbox';check.id='aceptacion-'+key;check.style.cssText='width:auto;margin-right:8px';label.append(check,document.createTextNode(key==='cuenta'?'Leí y acepto los términos de la plataforma.':declaration));}node.insertAdjacentElement('afterend',block);block.append(label);
 }
 function install(){for(const [key,selector]of Object.entries(targets)){const node=document.querySelector(selector);if(!node)continue;if(node.matches('select')&&!node.dataset.explanation77){node.dataset.explanation77='1';const p=document.createElement('p');p.className='small-muted';p.textContent=explanation;node.parentElement.insertAdjacentElement('afterend',p);node.parentElement.firstChild.textContent='¿Esta publicación es exclusivamente para mayores de 18 años?';}box(key,node.closest('label')||node);}
  const alta=document.getElementById('btnEnviarAltaAnunciante');if(alta&&!document.getElementById('alta-adulto')){const label=document.createElement('label');label.textContent='¿Esta publicación es exclusivamente para mayores de 18 años?';const select=document.createElement('select');select.id='alta-adulto';for(const [value,text]of [['false','No · Para cualquier público'],['true','Sí · Exclusivamente +18']]){const opt=document.createElement('option');opt.value=value;opt.textContent=text;select.append(opt);}label.append(select);const p=document.createElement('p');p.textContent=explanation;p.className='small-muted';alta.insertAdjacentElement('beforebegin',label);label.insertAdjacentElement('afterend',p);}
 }
 install();new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
 window.fetch=async function(input,init){const url=new URL(input instanceof Request?input.url:String(input),location.href);if(url.origin!==origin||String(init?.method||(input instanceof Request?input.method:'GET')).toUpperCase()!=='POST')return native(input,init);
  let body;try{body=JSON.parse(init?.body||'');}catch{return native(input,init);}
  const action=String(body.action||body.accion||'').toLowerCase();let key;
  if(url.pathname==='/events-new'&&['createfreeevent','updatefreeevent','createvipevent','updatevipevent'].includes(action))key=action.includes('free')?'free':'eventos';
  if(url.pathname==='/actividades'&&action==='guardar')key='actividades';if(url.pathname==='/publicidad'&&['guardar','save'].includes(action))key='publicidad';if(url.pathname==='/commerce'&&action==='set_datos')key='anunciante';if(url.pathname==='/suscriptores'&&action==='crear')key='cuenta';if(url.pathname==='/suscriptores'&&action==='solicitar_anunciante')key='alta';
  if(!key)return native(input,init);install();const check=document.getElementById(key==='free'?'evf-responsabilidad':'aceptacion-'+key);
  if(!check?.checked)return Response.json({success:false,message:'Aceptá los términos y la declaración de responsabilidad antes de continuar.'},{status:400});
  body.declaracion_publicacion={aceptada:true,version};if(key==='alta')body.contenido_adulto=document.getElementById('alta-adulto')?.value==='true';
  const response=await native(input,{...init,body:JSON.stringify(body)});response.clone().json().then(j=>{if(j.success)check.checked=false;}).catch(()=>{});return response;
 };
})();
