import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const byId=new Map(),selectors=new Map(),calls=[];
class Element{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.parentElement=null;this.style={};this.checked=false;}set id(v){this._id=v;byId.set(v,this)}get id(){return this._id}append(...nodes){for(const n of nodes){this.children.push(n);if(n&&typeof n==='object')n.parentElement=this}}get firstChild(){return this.children[0]}matches(s){return s==='select'&&this.tag==='select'}closest(s){if(s==='label')return this.tag==='label'?this:this.parentElement?.closest(s);return null}insertAdjacentElement(pos,node){node.parentElement=this.parentElement||body}querySelector(s){if(s==='span')return this.children.find(c=>c.tag==='span');return null}}
const body=new Element('body');for(const [key,selector]of [['eventos','#ev-adulto'],['actividades','#act-adulto'],['publicidad','#pub-adulto'],['anunciante','[name="contenido_adulto"]']]){const label=new Element('label'),text={textContent:'Contenido +18'},select=new Element('select');label.append(text,select);body.append(label);selectors.set(selector,select)}
for(const [id,selector]of [['btnEnviarAltaAnunciante','#btnEnviarAltaAnunciante'],['register-btn','#register-btn']]){const e=new Element('button');e.id=id;body.append(e);selectors.set(selector,e)}
const freeLabel=new Element('label'),freeSelect=new Element('select');freeLabel.append({textContent:'Contenido adulto'},freeSelect);selectors.set('#evf-adulto',freeSelect);body.append(freeLabel);const respLabel=new Element('label'),resp=new Element('input'),span=new Element('span');resp.id='evf-responsabilidad';respLabel.append(resp,span);body.append(respLabel);
const document={body,querySelector:s=>selectors.get(s)||null,getElementById:id=>byId.get(id)||null,createElement:tag=>new Element(tag),createTextNode:text=>({textContent:text})};
const window={fetch:async(input,init)=>{calls.push({input,body:JSON.parse(init.body)});return Response.json({success:true})}};vm.runInNewContext(fs.readFileSync(new URL('../plataforma/publicacion.js',import.meta.url),'utf8'),{window,document,location:{href:'https://test.invalid/'},MutationObserver:class{observe(){}},URL,Request,Response});
async function submit(path,body){return window.fetch('https://login.liqkoargentina.workers.dev'+path,{method:'POST',body:JSON.stringify(body)})}
for(const [key,path,action]of [['eventos','/events-new','createVipEvent'],['free','/events-new','createFreeEvent'],['actividades','/actividades','guardar'],['publicidad','/publicidad','guardar'],['anunciante','/commerce','set_datos'],['alta','/suscriptores','solicitar_anunciante'],['cuenta','/suscriptores','crear']]){
 const check=byId.get(key==='free'?'evf-responsabilidad':'aceptacion-'+key);assert.ok(check,key);const before=calls.length;let r=await submit(path,{action,payload:{nombre:'Prueba'}});assert.equal(r.status,400,key);assert.equal(calls.length,before,key);check.checked=true;r=await submit(path,{action,payload:{nombre:'Prueba'}});assert.equal(r.status,200,key);assert.deepEqual(calls.at(-1).body.declaracion_publicacion,{aceptada:true,version:'2026-10-10'});await r.json();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(check.checked,false,key);
}
assert.equal(byId.has('aceptacion-free'),false,'La declaración Free reutiliza su casilla, sin duplicarla.');assert.ok(span.textContent.includes('veraces'));assert.ok(byId.has('alta-adulto'));
console.log('UI V77 PASS: aceptación explícita en todos los formularios; bloquea envío sin aceptar, transmite versión y desmarca después de guardar; explicación y selector en alta; declaración Free única.');
