import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const html=fs.readFileSync('login-soporte.html','utf8'),a=html.indexOf('async function registrarSolicitudSoporteV73_'),b=html.indexOf('\nfunction abrirSolicitudAnunciante_',a),calls=[];
const fields={'recuperar-mail':{value:'persona@test.invalid'},'recuperar-msg':{textContent:'',appendChild(x){this.link=x}},'btnAyudaContrasenaWhatsapp':{disabled:false},'soporte-mail':{value:'persona@test.invalid'},'soporte-whatsapp':{value:'5491112345678'},'soporte-detalle':{value:'No puedo cargar mi actividad'},'soporte-msg':{textContent:''},'btnEnviarSoporte':{disabled:false}};
const context={WORKER_ORIGIN:'https://test.invalid',SUPPORT_NUMBER:'5491150972086',sesionSuscriptor:{nombre:'Persona',mail:'persona@test.invalid'},sesion:{id:'A'},document:{getElementById:id=>fields[id],createElement:()=>({})},gldAuthHeaders_:x=>({...x,Authorization:'Bearer valid-session'}),fetch:async(url,options)=>{calls.push({url,options,body:JSON.parse(options.body)});return{ok:true,json:async()=>({success:true,solicitud_id:'SOL-TEST'})}}};
vm.createContext(context);vm.runInContext(html.slice(a,b),context);
await context.solicitarAyudaContrasena_();assert.equal(calls[0].body.tipo,'RECUPERACION');assert.equal(calls[0].body.anunciante_id,'');assert.match(fields['recuperar-msg'].textContent,/registrada/);assert.match(fields['recuperar-msg'].link.href,/AYUDA_CONTRASENA/);assert.equal(fields['btnAyudaContrasenaWhatsapp'].disabled,false);
await context.enviarSoporteV73_();assert.equal(calls[1].body.tipo,'SOPORTE');assert.equal(calls[1].body.anunciante_id,'A');assert.equal(calls[1].body.detalle,'No puedo cargar mi actividad');assert.match(fields['soporte-msg'].textContent,/pendiente de atención/);assert.equal(fields['btnEnviarSoporte'].disabled,false);
context.fetch=async()=>({ok:false,json:async()=>({success:false,message:'No disponible'})});await context.solicitarAyudaContrasena_();assert.match(fields['recuperar-msg'].textContent,/No disponible/);assert.equal(fields['recuperar-msg'].link.textContent,'Contactar por WhatsApp');
console.log('UI V73: ayuda de acceso y soporte diferenciados, confirmación correcta y WhatsApp disponible si el registro falla.');
